import { UserRole } from "../../generated/prisma-client";
import { EnterpriseRole, toEnterpriseRole } from "@/lib/rbac";

export type DashboardWidget =
  | "RECEIVABLES"
  | "PAYABLES"
  | "PENDING_ADVANCES"
  | "PENDING_APPROVALS"
  | "MISSING_DOCUMENTS"
  | "OVER_BUDGET_PROJECTS"
  | "LOSS_PROJECTS"
  | "OPEN_PERIODS"
  | "CASH_FLOW"
  | "PROFIT"
  | "AUDIT_ALERTS";

const DASHBOARD_MATRIX: Record<EnterpriseRole, DashboardWidget[]> = {
  KE_TOAN_CONG_NO: ["RECEIVABLES", "PAYABLES", "PENDING_APPROVALS", "MISSING_DOCUMENTS"],
  KE_TOAN_THANH_TOAN: ["PAYABLES", "PENDING_ADVANCES", "PENDING_APPROVALS", "CASH_FLOW"],
  KE_TOAN_TONG_HOP: ["RECEIVABLES", "PAYABLES", "PENDING_APPROVALS", "MISSING_DOCUMENTS", "OPEN_PERIODS"],
  KE_TOAN_TRUONG: ["RECEIVABLES", "PAYABLES", "PENDING_ADVANCES", "PENDING_APPROVALS", "MISSING_DOCUMENTS", "OVER_BUDGET_PROJECTS", "LOSS_PROJECTS", "OPEN_PERIODS", "CASH_FLOW", "PROFIT"],
  GIAM_DOC: ["RECEIVABLES", "PAYABLES", "OVER_BUDGET_PROJECTS", "LOSS_PROJECTS", "CASH_FLOW", "PROFIT", "AUDIT_ALERTS"],
  BAN_KIEM_SOAT: ["PENDING_APPROVALS", "MISSING_DOCUMENTS", "OVER_BUDGET_PROJECTS", "LOSS_PROJECTS", "AUDIT_ALERTS"],
  QUAN_TRI_HE_THONG: ["RECEIVABLES", "PAYABLES", "PENDING_ADVANCES", "PENDING_APPROVALS", "MISSING_DOCUMENTS", "OVER_BUDGET_PROJECTS", "LOSS_PROJECTS", "OPEN_PERIODS", "CASH_FLOW", "PROFIT", "AUDIT_ALERTS"],
};

export class DashboardGovernance {
  static widgetsForRole(role: UserRole): DashboardWidget[] {
    return DASHBOARD_MATRIX[toEnterpriseRole(role)];
  }
}
