const fs = require('fs');
const path = require('path');

const roots = ['app', 'components', 'app/components', 'services', 'lib', 'styles', 'public'];
const exts = new Set(['.ts', '.tsx', '.js', '.jsx', '.css']);

const patterns = [
  {
    key: 'hardcode_hex_or_rgb',
    sev: 'Critical',
    // hard-coded hex/rgb/rgba or tailwind arbitrary color syntax like bg-[#...]
    re: /(bg-\[\#|text-\[\#|border-\[\#|from-\[\#|to-\[\#|rgb\(|rgba\(|#[0-9a-fA-F]{3,8})/g,
  },
  {
    key: 'tailwind_risky_gray_zinc_slate',
    sev: 'High',
    re: /(bg-zinc|text-zinc|border-zinc|bg-gray|text-gray|border-gray|bg-slate|text-slate|border-slate)/g,
  },
  {
    key: 'tailwind_style_deviation',
    sev: 'Medium',
    re: /(shadow-2xl|shadow-xl|rounded-\[|text-\[11px\]|text-\[13px\]|p-\[|m-\[)/g,
  },
  {
    key: 'manual_html_table',
    sev: 'High',
    re: /(<table\b|<thead\b|<tbody\b|<tr\b|<td\b|<th\b)/g,
  },
  {
    key: 'english_ui_quotes',
    sev: 'High',
    // quoted English-ish phrases (heuristic)
    re: /("[A-Za-z][A-Za-z0-9 ,.'!?&()/:-]{2,}"|\'[A-Za-z][A-Za-z0-9 ,.'!?&()/:-]{2,}\'|\>[A-Za-z][A-Za-z0-9 ,.'!?&()/:-]{2,}<)/g,
  },
  {
    key: 'ui_prop_keywords_english',
    sev: 'Medium',
    // UI prop attribute names that often contain user-visible strings
    re: /(placeholder=|title=|aria-label=|toast|message|description|label|empty|error|success|warning|loading)/gi,
  },
];

function listFilesRecursive(root) {
  const out = [];
  function walk(d) {
    for (const ent of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, ent.name);
      if (ent.isDirectory()) {
        if (['node_modules', '.next', 'out', 'generated', 'dist'].includes(ent.name)) continue;
        walk(p);
      } else {
        if (exts.has(path.extname(ent.name))) out.push(p);
      }
    }
  }
  if (fs.existsSync(root)) walk(root);
  return out;
}

function scanFiles(files) {
  const matches = {};
  for (const f of files) {
    let txt = '';
    try {
      txt = fs.readFileSync(f, 'utf8');
    } catch {
      continue;
    }
    const lines = txt.split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      for (const pat of patterns) {
        pat.re.lastIndex = 0;
        const m = line.match(pat.re);
        if (m) {
          if (!matches[pat.key]) matches[pat.key] = [];
          matches[pat.key].push({
            file: f,
            line: i + 1,
            content: line.trim().slice(0, 300),
            sev: pat.sev,
          });
        }
      }
    }
  }
  return matches;
}

function findAppPages() {
  const pages = [];
  const appRoot = 'app';
  if (!fs.existsSync(appRoot)) return pages;

  function walk(d) {
    for (const ent of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, ent.name);
      if (ent.isDirectory()) {
        if (['node_modules', '.next', 'out'].includes(ent.name)) continue;
        walk(p);
      } else {
        if (ent.isFile() && p.endsWith(path.join('page.tsx')) && p.startsWith('app' + path.sep)) {
          pages.push(p);
        }
      }
    }
  }

  walk(appRoot);
  return pages;
}

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '<').replace(/>/g, '>');
}

fs.mkdirSync('docs/ui-ux', { recursive: true });

const outputs = {};
let totalFilesScanned = 0;

for (const r of roots) {
  const exists = fs.existsSync(r);
  if (!exists) {
    outputs[r] = { root: r, exists: false, filesScanned: 0, matches: {} };
    continue;
  }

  const files = listFilesRecursive(r);
  totalFilesScanned += files.length;
  const matches = scanFiles(files);

  const res = { root: r, exists: true, filesScanned: files.length, matches };
  outputs[r] = res;

  const safeName = r.replace(/\//g, '-');
  const outPath = `docs/ui-ux/audit-temp-${safeName}.json`;
  fs.writeFileSync(outPath, JSON.stringify(res, null, 2));
}

// merge matches across roots (only the match objects we have)
const allMatches = {};
for (const r of roots) {
  const m = (outputs[r] && outputs[r].matches) || {};
  for (const key of Object.keys(m)) {
    if (!allMatches[key]) allMatches[key] = [];
    allMatches[key] = allMatches[key].concat(m[key]);
  }
}

const counts = {};
for (const key of Object.keys(allMatches)) {
  counts[key] = allMatches[key].length;
}

const pages = findAppPages();

// Build report
let md = [];
md.push('# Full UI Redesign Forensic Inventory Audit');
md.push('');
md.push('Generated by Node.js regex scanner (Phase 1 audit only).');
md.push('');
md.push('## 0) Stats');
md.push(`- Total files scanned: **${totalFilesScanned}**`);
md.push(`- Total route/page files found (app/**/page.tsx): **${pages.length}**`);
md.push('');

md.push('## 1) Routes/Page list');
md.push('');
md.push('```');
md.push(pages.sort().join('\n'));
md.push('```');
md.push('');

md.push('## 2) Screens checked list (heuristic)');
md.push('- Dashboard / Tổng quan');
md.push('- Projects / Công trình / Dự án');
md.push('- WBS / Hạng mục');
md.push('- Budget / Dự toán');
md.push('- Costs / Chi phí');
md.push('- Debt / Công nợ');
md.push('- Cash & Bank / Quỹ & Ngân hàng');
md.push('- Inventory / Kho & Vật tư');
md.push('- Reports / Báo cáo');
md.push('- Reports Inventory / Báo cáo kho');
md.push('- Suppliers / Nhà cung cấp');
md.push('- Contracts / Hợp đồng');
md.push('- Advances / Tạm ứng');
md.push('- Payments / Thanh toán');
md.push('- Tax / Thuế');
md.push('- Invoices / Hóa đơn');
md.push('- System / Hệ thống');
md.push('- Print pages / Trang in');
md.push('- Modal/Drawer/Dialog/Toast/Empty/Loading/Error state');
md.push('');

function addTopList(sectionTitle, key) {
  const arr = allMatches[key] || [];
  md.push(sectionTitle);
  md.push('');
  md.push(`- Count: **${arr.length}**`);
  md.push('');
  arr.slice(0, 200).forEach((r) => {
    md.push(`- **[${r.sev}]** ${r.file}:${r.line} | ${escapeHtml(r.content)}`);
  });
  if (arr.length > 200) md.push(`- ... (+${arr.length - 200} more)`);
  md.push('');
}

addTopList('## 3) Hard-coded colors list', 'hardcode_hex_or_rgb');
addTopList('## 4) Manual HTML table usage list', 'manual_html_table');

// keyword-based lists
addTopList('## 5) Modal/form/button/state inconsistencies (keyword heuristic)', 'ui_prop_keywords_english');
addTopList('## 6) English UI text occurrences (suspected)', 'english_ui_quotes');
addTopList('## 7) Light/Dark mismatch list (heuristic via risky colors)', 'tailwind_risky_gray_zinc_slate');

md.push('## 8) Priority fix plan');
md.push('### Critical');
md.push('- Replace all hard-coded HEX/RGB and arbitrary Tailwind colors with CSS variables (enterprise design tokens).');
md.push('### High');
md.push('- Replace risky tailwind gray/zinc/slate with semantic theme tokens.');
md.push('- Replace manual <table> implementations with EnterpriseTable for consistent spacing/alignment/theme behavior.');
md.push('### Medium');
md.push('- Remove style deviation utilities and migrate to unified tokens.');
md.push('');
md.push('---');
md.push('## 9) Phase 1 output summary (counts by group)');
md.push('');
md.push('```');
for (const [k, v] of Object.entries(counts)) {
  md.push(`${k}: ${v}`);
}
md.push('```');

const reportPath = 'docs/ui-ux/full-ui-redesign-audit.md';
fs.writeFileSync(reportPath, md.join('\n'));

console.log('DONE: report written:', reportPath);

